# Install conda environment using this: conda env create -f environment.yml

name: Denoising_env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - appdirs=1.4.4
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - contourpy=1.2.0
  - cycler=0.11.0
  - dav1d=1.2.1
  - docker-pycreds=0.4.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - giflib=5.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - idna=3.7
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - jpeg=9e
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.4
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.9.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - networkx=3.2.1
  - numexpr=2.10.1
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.2.2
  - pip=24.2
  - platformdirs=3.10.0
  - protobuf=4.25.3
  - psutil=5.9.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.9.20
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - scikit-image=0.24.0
  - scipy=1.12.0
  - seaborn=0.13.2
  - sentry-sdk=1.9.0
  - setproctitle=1.2.2
  - setuptools=75.1.0
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tifffile=2023.4.12
  - tk=8.6.14
  - typing_extensions=4.11.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wandb=0.16.6
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zfp=1.0.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - filelock==3.16.1
    - fsspec==2024.10.0
    - jinja2==3.1.4
    - markupsafe==3.0.2
    - mpmath==1.3.0
    - numpy==2.0.2
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - opencv-python==4.10.0.84
    - pillow==11.0.0
    - sympy==1.13.1
    - torch==2.5.1
    - torchaudio==2.5.1
    - torchvision==0.20.1
    - triton==3.1.0
    - typing-extensions==4.12.2